apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


############Pod file usingov and pvc#################3

---
apiVersion: v1
kind: pod
metadata:
  name: nginx-pod-pvc
spec:
  containers:
    - name: nginx
      image: nginx-1.14.2
      command: ["sh","-c","sleep 3600"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: nginx-persistent-storage
  volumes:
    - name: nginx-persistent-storage
      PersistentVolumeClaim:
        claimName: pvc-nginx

