apiVersion: v1
kind: secret
metadata:
  name: nginx-secret
type: opaque
data:
  username: admin #has to be encoded in base63 format
  password: admin123 # has to be encoded in base64 format


#####use of secret in pod######################3
---
apiVersion: v1
kind: pod
metadata: 
  name: nginx-secret-pod
spec:
  containers:
    - name: nginx
      image: nginx-1.14.2
      command: ["sh", "-c", "echo $(username) $(password) && sleep 3600"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password

